version: '3.8'

services:
  app:
    build: ./
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $PG_DB -U $PG_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5